#!/usr/bin/env node
/**
 * Bundles src/puffer-card.js into dist/puffer-card.js.
 *
 * What the build does that the old hand-written dist/ could not:
 *   - inlines Lit, so the card no longer pulls it from a CDN at runtime;
 *   - inlines src/translations/ *.json, so there is no runtime fetch and the
 *     card is a single self-contained file;
 *   - substitutes the __VERSION__ placeholder, so the version string can never
 *     drift from the tag.
 *
 * Version resolution:
 *   PUFFER_VERSION env var (set from the git tag by the release workflow),
 *   falling back to "version" in package.json for local and CI builds.
 *
 * Usage: node scripts/build.mjs
 */

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import * as esbuild from "esbuild";

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");

const pkg = JSON.parse(readFileSync(path.join(ROOT, "package.json"), "utf8"));
const version = process.env.PUFFER_VERSION || pkg.version;

if (!version) {
  console.error("No version available (PUFFER_VERSION unset and package.json has no version).");
  process.exit(1);
}

const entry = path.join(ROOT, "src", "puffer-card.js");
const outfile = path.join(ROOT, "dist", "puffer-card.js");

await esbuild.build({
  entryPoints: [entry],
  outfile,
  bundle: true,
  format: "esm",
  target: "es2021",
  minify: true,
  // Keeps Lit's BSD-3 license banner at the end of the bundle, as required
  // when redistributing it.
  legalComments: "eof",
  // The card is a single file by design: dist/ must never contain anything
  // else, because once a release asset is attached HACS switches to
  // single-file installs and would stop downloading companion files.
  sourcemap: false,
  define: {
    __VERSION__: JSON.stringify(version),
  },
  banner: {
    js:
      `/*! Puffer Card v${version} | MIT | https://github.com/naked-head/puffer-card\n` +
      ` *  Generated by scripts/build.mjs — do not edit this file by hand.\n` +
      ` *  Bundles Lit v${pkg.dependencies.lit} (BSD-3-Clause, see notice at the end of this file). */`,
  },
});

console.log(`Built dist/puffer-card.js (version ${version})`);
